FROM php:apache

# Extensions per MySQL
RUN docker-php-ext-install pdo_mysql mysqli

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Paquets del sistema necessaris per MongoDB i Composer
RUN apt-get update && apt-get install -y \
    unzip \
    zip \
    libssl-dev \
    pkg-config

# Extensió MongoDB per PHP (via PECL)
RUN pecl install mongodb && docker-php-ext-enable mongodb

